<?php
session_start();
unset($_SESSION["id"]);
unset($_SESSION["name"]);
unset($_SESSION["surname"]);
unset($_SESSION["email"]);
unset($_SESSION["location"]);
header("Location:../index.php");
?>